version: '3.8'

services:

  database:
    container_name: wish-mysqldb
    image: mysql:8.0.35
    environment:
      - MYSQL_DATABASE=wish-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    healthcheck:
      # test: [ "CMD", "/usr/bin/mysql", "--user=root",  "--password=root", "--execute", "SHOW DATABASES;" ]
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot --silent"]
      interval: 5s
      timeout: 30s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - backend-network


  backend:
    container_name: wish-backend-app
    image: sufailbadushat/wish-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/wish-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health || exit 1"]
      test: ["CMD-SHELL", "curl -f -X POST -H 'Content-Type: application/json' -d '{\"username\": \"sufail@gmail.com\", \"password\": \"admin\"}' http://localhost:8081/auth/signIn || exit 1"]
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - backend-network
      - frontend-network


  frontend:
    container_name: wish-frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    image: sufailbadushat/wish-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 4200:4200
    networks:
      - frontend-network


volumes:
  mysql-data:


networks:
  frontend-network:
  backend-network:
    

  